### ISSUE TITLE
Natives errors

### ISSUE THREAD

**Issue by kmsraidboss** [dubbeh/motd-fixer-plugin#1]
I recently noticed that this plugin stopped working when some errors started coming up. Here is the following from my SM Error Logs:

`L 11/10/2017 - 07:20:47: [SMJSON] Error in line 1, col 1: '[' or '{' expected near '<'
L 11/10/2017 - 07:20:47: [SM] Exception reported: Handle 623c3e62 is invalid (error 4)
L 11/10/2017 - 07:20:47: [SM] Blaming: motdf.smx
L 11/10/2017 - 07:20:47: [SM] Call stack trace:
L 11/10/2017 - 07:20:47: [SM]   [0] CloseHandle
L 11/10/2017 - 07:20:47: [SM]   [1] Line 231, 
motdf/natives.sp::SteamWorks_OnClientURLRegisterComplete`

The following is getting spammed in my standard SM logs: 

`L 11/10/2017 - 07:13:50: [motdf.smx] Error parsing JSON Response.
L 11/10/2017 - 07:13:50: [motdf.smx] Error:  - Is Server Blocked: No`

The following is logged in standard SM logs when I do motdf_register:

`L 11/10/2017 - 07:14:08: [motdf.smx] Command_MOTDRegisterServer () Registering server.
L 11/10/2017 - 07:14:08: [motdf.smx] Error parsing JSON Response.
L 11/10/2017 - 07:14:08: [motdf.smx] SteamWorks_OnRegisterComplete() Error:  - Is Server Blocked: No`

Lastly, this is logging in standard SM logs every time the native MOTDF_ShowMotdPanel is called:

`L 11/10/2017 - 07:14:46: [motdf.smx] SetClientRequestData() Error: Unable to set Client IP, Auth ID or Server Info.`

My Sourcemod is up to date with the latest stable version. Both my motdf plugin and web setup are up to date with your current github version. The correct base url and token is set. It was working fine but I think it's been a week or so now that this started happening, after one of the recent CSGO updates. So the plugin is essentially broken for me as of right now. 

Edit - sorry for the shit formatting I'm relatively new to using github

**Comment by dubbeh** [comment]
Released an update today (v1.07) that should hopefully address them issues or at least give more feedback on the potential errors.

The plugin will now dump the request result inside the server log files - if json_load returns a bad value. Actually sounds like it's something to do with the PHP script instead of the plugin.

Feel free to report back if the issue is resolved or you still have the problem - should be much easier to pin-point exactly where things are going wrong.
